### ISSUE TITLE
Please explain this issue

### ISSUE THREAD

**Issue by arungoyal** [igalata/Bubble-Picker#42]
Process: com.multitv.yuv, PID: 32613
                                                                kotlin.UninitializedPropertyAccessException: lateinit property items has not been initialized
                                                                    at com.igalata.bubblepicker.rendering.PickerRenderer.initialize(PickerRenderer.kt:79)
                                                                    at com.igalata.bubblepicker.rendering.PickerRenderer.onSurfaceChanged(PickerRenderer.kt:67)
                                                                    at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1519)
                                                                    at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

**Comment by hussi1** [comment]
did you find solution for this ?

**Comment by amixpal** [comment]
I am also facing the same problem.

**Comment by ArsalRaza** [comment]
i am also facing this issue!!

**Comment by ismailtosun** [comment]
same problem

**Comment by hantrungkien** [comment]
@arungoyal @hussi1 @amixpal @ArsalRaza @ismailtosun 
please review my lib was developed based on this lib. This is a conflict between java and kotlin library and I fixed this issue
https://github.com/hantrungkien/Bubble-Picker
