### ISSUE TITLE
Please help me i am getting this error

### ISSUE THREAD

**Issue by iamjitendrasinh** [igalata/Bubble-Picker#51]
kotlin.UninitializedPropertyAccessException: lateinit property items has not been initialized
                                                       at com.igalata.bubblepicker.rendering.PickerRenderer.initialize(PickerRenderer.kt:79)
                                                       at com.igalata.bubblepicker.rendering.PickerRenderer.onSurfaceChanged(PickerRenderer.kt:67)
                                                       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1532)
                                                       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)

@igalata please help me out

**Comment by ghost** [comment]
I am also getting this error :(

**Comment by hantrungkien** [comment]
@iamjitendrasinh @mongkonsrisin 
please review my lib was developed based on this lib. I fixed this issue
https://github.com/hantrungkien/Bubble-Picker

**Comment by daiwenbo88** [comment]
我知道这么解决：
```
//delete     lateinit 
class PickerRenderer(val glView: View) : GLSurfaceView.Renderer {
   ...............
   var items: ArrayList<PickerItem> = ArrayList();
   ................

 //add if(..)
  private fun initialize() {
        if (items.isEmpty()) {
            return;
        }
        ..................
    }
}
```
