### ISSUE TITLE
How to make select some bubbles when open bubble activity again.

### ISSUE THREAD

**Issue by chetanya19** [igalata/Bubble-Picker#64]

**Comment by tabish075** [comment]
have you found a solution, I am getting this error

`android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6898)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1083)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5205)
        at android.view.View.invalidateInternal(View.java:13680)
        at android.view.View.invalidate(View.java:13644)
        at android.view.View.invalidate(View.java:13628)
        at android.widget.ImageView.invalidateDrawable(ImageView.java:255)
        at android.graphics.drawable.Drawable.invalidateSelf(Drawable.java:435)
        at android.graphics.drawable.Drawable.setBounds(Drawable.java:214)
        at android.graphics.drawable.Drawable.setBounds(Drawable.java:226)
        at com.kienht.bubblepicker.rendering.Item.drawIcon(Item.kt:194)
        at com.kienht.bubblepicker.rendering.Item.createBitmap(Item.kt:126)
        at com.kienht.bubblepicker.rendering.Item.bindTexture(Item.kt:217)
        at com.kienht.bubblepicker.rendering.Item.bindTextures(Item.kt:86)
        at com.kienht.bubblepicker.rendering.PickerRenderer.initializeItem(PickerRenderer.kt:130)
        at com.kienht.bubblepicker.rendering.PickerRenderer.initializeArrays(PickerRenderer.kt:122)
        at com.kienht.bubblepicker.rendering.PickerRenderer.initialize(PickerRenderer.kt:116)
        at com.kienht.bubblepicker.rendering.PickerRenderer.onSurfaceChanged(PickerRenderer.kt:85)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1532)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1259)
`
