### ISSUE TITLE
How to notifydata for Bubble Picker Please Response ASAP

### ISSUE THREAD

**Issue by RapoluSaikrishnaRao** [igalata/Bubble-Picker#65]
Hi am using this Libruary in my app.how do we get position in onBubbleselected Listener and also how to notify data when array size is changed for bubble pickers.Please Response ASAP.

And also the below Exception am getting
FATAL EXCEPTION: GLThread 952
                                                                         PID: 6185
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'org.jbox2d.collision.shapes.Shape org.jbox2d.dynamics.Fixture.getShape()' on a null object reference
                                                                             at com.igalata.bubblepicker.physics.CircleBody.reset(CircleBody.kt:91)
                                                                             at com.igalata.bubblepicker.physics.CircleBody.increase(CircleBody.kt:82)
                                                                             at com.igalata.bubblepicker.physics.CircleBody.resize(CircleBody.kt:66)
                                                                             at com.igalata.bubblepicker.physics.Engine.move(Engine.kt:55)
                                                                             at com.igalata.bubblepicker.rendering.PickerRenderer.onDrawFrame(PickerRenderer.kt:67)
                                                                             at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
                                                                             at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1237)

**Comment by DrewGregory** [comment]
To those who may find this interesting...
it seems to me that you can reinitialize the rendering by resetting its visibility. Just try `picker.setVisibility(View.GONE);` followed by `picker.setVisibility(View.VISIBLE);`

The developer suggested calling `picker.onPause()` followed by `picker.onResume()`, but I did not achieve desired behavior with those methods.
