### ISSUE TITLE
exception

### ISSUE THREAD

**Issue by yoonah5959** [igalata/Bubble-Picker#93]
I cloned your git url and run the app.
I get this error when I go back to home screen with back key and click your app again.

2021-07-17 14:46:57.470 18102-18272/com.igalata.bubblepickerdemo E/AndroidRuntime: FATAL EXCEPTION: GLThread 34865
    Process: com.igalata.bubblepickerdemo, PID: 18102
    java.lang.AssertionError
        at org.jbox2d.collision.broadphase.DynamicTree.destroyProxy(DynamicTree.java:115)
        at org.jbox2d.collision.broadphase.BroadPhase.destroyProxy(BroadPhase.java:104)
        at org.jbox2d.dynamics.Fixture.destroyProxy(Fixture.java:314)
        at org.jbox2d.dynamics.World.destroyBody(World.java:344)
        at com.igalata.bubblepicker.physics.Engine.clear(Engine.kt:85)
        at com.igalata.bubblepicker.rendering.PickerRenderer.clear(PickerRenderer.kt:169)
        at com.igalata.bubblepicker.rendering.PickerRenderer.initialize(PickerRenderer.kt:77)
        at com.igalata.bubblepicker.rendering.PickerRenderer.onSurfaceChanged(PickerRenderer.kt:67)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1575)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

**Comment by IgnaGarcia** [comment]
same problem
